"""initial schema (12 tables)

Revision ID: c0d4993bb6f1
Revises: 
Create Date: 2026-05-15 00:24:50.241826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d4993bb6f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('reddit_post_id', sa.String(length=16), nullable=False),
    sa.Column('subreddit', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('permalink', sa.String(length=255), nullable=True),
    sa.Column('author_username', sa.String(length=64), nullable=True),
    sa.Column('author_karma', sa.Integer(), nullable=True),
    sa.Column('author_created_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('discovery_source', sa.String(length=64), nullable=True),
    sa.Column('initial_score', sa.Integer(), nullable=True),
    sa.Column('initial_num_comments', sa.Integer(), nullable=True),
    sa.Column('upvote_ratio', sa.Float(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_posts_author_username'), ['author_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_posts_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_posts_reddit_post_id'), ['reddit_post_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidate_posts_subreddit'), ['subreddit'], unique=False)

    op.create_table('keyword_seeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_candidates_yielded', sa.Integer(), nullable=False),
    sa.Column('total_promoted', sa.Integer(), nullable=False),
    sa.Column('total_collected', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_seeds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_seeds_keyword'), ['keyword'], unique=True)

    op.create_table('llm_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('context_ref', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_records_purpose'), ['purpose'], unique=False)

    op.create_table('subreddit_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('lang_hint', sa.String(length=8), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_candidates_yielded', sa.Integer(), nullable=False),
    sa.Column('total_promoted', sa.Integer(), nullable=False),
    sa.Column('total_collected', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subreddit_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subreddit_sources_name'), ['name'], unique=True)

    op.create_table('daily_pushes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('push_date', sa.Date(), nullable=False),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('push_type', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_date', 'candidate_post_id', name='uq_push_date_candidate')
    )
    with op.batch_alter_table('daily_pushes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_pushes_push_date'), ['push_date'], unique=False)

    op.create_table('feedback',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('acted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scoring_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('candidate_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('polling_tier', sa.String(length=16), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('initial_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_post_id'], ['candidate_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('upvote_ratio', sa.Float(), nullable=True),
    sa.Column('new_comments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('tracked_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reddit_post_id', sa.String(length=16), nullable=True),
    sa.Column('relation_type', sa.String(length=16), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_post_id'], ['tracked_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('related_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_related_posts_reddit_post_id'), ['reddit_post_id'], unique=False)

    op.create_table('qa_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('qa_session_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['qa_session_id'], ['qa_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa_messages')
    with op.batch_alter_table('related_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_related_posts_reddit_post_id'))

    op.drop_table('related_posts')
    op.drop_table('qa_sessions')
    op.drop_table('post_snapshots')
    op.drop_table('tracked_posts')
    op.drop_table('scoring_records')
    op.drop_table('feedback')
    with op.batch_alter_table('daily_pushes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_pushes_push_date'))

    op.drop_table('daily_pushes')
    with op.batch_alter_table('subreddit_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subreddit_sources_name'))

    op.drop_table('subreddit_sources')
    with op.batch_alter_table('llm_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_records_purpose'))

    op.drop_table('llm_records')
    with op.batch_alter_table('keyword_seeds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_seeds_keyword'))

    op.drop_table('keyword_seeds')
    with op.batch_alter_table('candidate_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_posts_subreddit'))
        batch_op.drop_index(batch_op.f('ix_candidate_posts_reddit_post_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_posts_posted_at'))
        batch_op.drop_index(batch_op.f('ix_candidate_posts_author_username'))

    op.drop_table('candidate_posts')
    # ### end Alembic commands ###
